config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :books do
    resources :listings, only: [:new, :create, :delete]
    resources :comments, only: [:new, :create, :delete]
  end
  resources :lists do
    resources :listings, only: [:new, :create, :delete]
  end
  resources :listings

  # get "listings", to: "listings#index"
  # get "books/:id", to: "listings#new"
  # post "books/:id", to: "listings#create"
  # get "list/:id", to: "listings#index"
  # get "listings/:id/edit", to: "listings#edit", as: :listings_edit
  # patch "listings/:id", to: "listings#update"
  # delete "listings/:id", to: "listings#destroy"
  # Defines the root path route ("/")
  # root "articles#index"

  # get "lists", to: "lists#index"
  # get "lists", to: "lists#new"
  # # get "lists/new", to: "lists#new"
  # post "lists", to: "lists#create"
  # get "lists/:id", to: "lists#show", as: :list
  # get "lists/:id/edit", to: "lists#edit", as: :list_edit
  # patch "lists/:id", to: "lists#update"
  # delete "lists/:id", to: "lists#destroy"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :listings, dependent: :destroy
  has_many :comments, dependent: :destroy
  validates :status, acceptance: { accept: ["read", "unfinished", "currently reading", "not read"]}
  validates :pages, numericality: { only_integer: true, allow_nil: true }
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :book
  belongs_to :user
end

app/models/list.rb
class List < ApplicationRecord
  belongs_to :user
  has_many :listings, dependent: :destroy
  has_many :books, through: :listings
  validates :name, presence: true
  validates :name, uniqueness: { message: "You have a list named like this"}
end

app/models/listing.rb
class Listing < ApplicationRecord
  belongs_to :book
  belongs_to :list
  validates :book_id, uniqueness: {scope: :list_id, message: "You already have this on the list" }
  # validates_uniqueness_of :book_id, scope: :list_id, { message: }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]
  def index
    @books = Book.all
    @lists = List.all
  end

  def show
    @comment = Comment.new
    # @comments = Comment.where(book: @book)
    @listing = Listing.new
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to books_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    @book.update(book_params)
    if @book.save
      redirect_to book_path(@book)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @book.destroy
    redirect_to books_path, status: :see_other
  end

  private

  def book_params
    params.require(:book).permit(:title, :writer, :year, :language, :genree, :pages, :status, :date_finished, :print, :purchased, :lended, :lended_to, :location)
  end

  def set_book
    @book = Book.find(params[:id])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_book, only: [:new, :create, :destroy]

  def new
    @comment = Comment.new
  end

  def create
    @comment = Comment.new(comment_params)
    @comment.user_id = current_user.id
    @comment.book = @book
    # I deleted the two id-s
    if @comment.save
      redirect_to book_path(@book)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @comment.destroy
  end

  private

  def set_book
    @book = Book.find(params[:book_id])
  end

  def comment_params
    params.require(:comment).permit(:comment, :review, :rating)
  end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :set_book, only: [:new, :create]
  before_action :set_listing, only: [:show, :edit, :update, :destroy]

  def index
    @listings = Listing.all
  end

  def new
    @listing = Listing.new
  end

  def create
    @listing = Listing.new(listing_params)
    # checks if we are on the book page or the listings page
    @listing.book_id.nil? ? @listing.book_id = params[:book_id] : ""
    @listing.list_id.nil? ? @listing.list_id = params[:list_id] : ""
    if params[:book_id]
      if @listing.save
        redirect_to book_path(@listing.book)
      else
        render :new, status: :unprocessable_entity
      end
    else
      if @listing.save
        redirect_to list_path(@listing.list)
      else
        render :new, status: :unprocessable_entity
      end
    end
  end

  def edit
  end

  def update
    @listing.update(listing_params)
    if @listing.save
      redirect_to books_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @listing.destroy
  end

  private

  def listing_params
    params.require(:listing).permit(:comment, :book_id, :list_id)
  end

  # I kept the route for listings/new. But if there is a book_id in the params
  # because that means we are on the book/:id page and then I want to set the book
  def set_book
    params.key?(:book_id) ? @book = Book.find(params[:book_id]) : ""
  end


  def set_listing
    @listing = Listing.find(params[:id])
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show, :edit, :update, :destroy]

  def index
    @lists = List.all
    @list = List.new
  end

  def show
    @listing = Listing.new
  end

  def new
    @list = List.new
    @listing = Listing.new
  end

  def create
    @list = List.new(list_params)
    @list.user_id = current_user.id
    if @list.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    @list.update(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @list.destroy
    redirect_to lists_path, status: :see_other
  end

  private

  def list_params
    params.require(:list).permit(:name, :comment)
  end

  def set_list
    @list = List.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
    @books = Book.all
    @lists = List.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/books/_form.html.erb
<%# ||||||||||||||||||||||||||||||||||||||||||||||| %>
<%# This is the book form. I need to make it prettier %>

<%= link_to "back", :back, class: "btn btn-primary" %>


  <%= simple_form_for(book) do |f| %>
  <%= f.input :title %>
  <%= f.input :writer %>
  <%= f.input :year, placeholder: "only year, eg.: 2016, 2020" %>
  <%= f.input :language %>
  <%= f.input :genree %>
  <%= f.input :pages, placeholder: "only numbers, eg.: 315, 180" %>
  <%= f.input :status, selected: "not read", collection: ["read", "not read", "unfinished", "currently reading" ] %>
  <%= f.input :date_finished, html5: true  %>
  <%= f.input :print, collection: ["Printed", "E-book", "other"] %>
  <%= f.input :purchased, html5: true %>
  <%= f.input :lended %>
  <%= f.input :lended_to %>
  <%= f.input :location %>
  <%= f.submit :"Save", class: "btn btn-primary" %>
  <% end %>

app/views/books/edit.html.erb
<%= render "form", book: @book %>

app/views/books/index.html.erb
<%# ||||||||||||||||||||||||||||||||||||||||||||||| %>
<%#  %>

<h1>Book</h1>


<%# ||||||||||||||||||||||||||||||||||||||||||||||| %>
<%# Here I will add the javascript on the lists There will be all books function %>
<%# So the javascript will show everything based on the list we choose %>

<p>Lists</p>
  <% @lists.each do |list| %>
        <%= link_to list_path(list) do %>
  |<strong><%= list.name %></strong> |
    <% end %>
  <% end %>
  <hr>

  <%= link_to "New list", new_list_path, class: "btn btn-primary" %>
  <%= link_to "New book", new_book_path, class: "btn btn-primary" %>

<div class="container">
  <% @books.each do |book| %>
        <%= link_to book_path(book) do %>
        <div class="book">
        <h2><%= book.title %></h2>
        <p><%= book.writer%></p>
        </div>
        <% end %>
      <% end %>
</div>





<%# have a button to go to the list %>

app/views/books/new.html.erb
<h1>book new</h1>

<%= simple_form_for(@book) do |f| %>
<%= f.input :title %>
<%= f.input :writer %>
<%= f.input :year %>
<%= f.input :language %>
<%= f.input :genree %>
<%= f.input :pages %>
<%= f.input :status %>
<%= f.input :date_finished, html5: true  %>
<%= f.input :print %>
<%= f.input :purchased, html5: true %>
<%= f.input :lended %>
<%= f.input :lended_to %>
<%= f.input :location %>
<%= f.submit :"Save", class: "btn btn-primary" %>
<% end %>

app/views/books/show.html.erb
<h1> <strong><%=@book.title %></strong> showpage</h1>
<h3><strong>title: </strong> <%= @book.title %></h3>
<h4><strong>Writer: </strong> <%= @book.writer %></h4>
<p><strong>Year purchased: </strong><%= @book.purchased.nil? ? "" : @book.purchased.year %></p>
<p><strong>Status</strong> <%= @book.status %></p>
<p><strong>Year published: </strong> <%= @book.year %></p>
<p><strong>Language: </strong><%= @book.language %></p>
<p><strong>Genre: </strong><%= @book.genree %></p>
<p><strong>Purchased: </strong><%= @book.purchased %></p>
<p><strong>Lended: </strong><%= @book.lended %></p>
<p><strong>Lended to: </strong><%= @book.lended_to %></p>
<p><strong>Location of the book: </strong><%= @book.location %></p>
<p><strong>Print: </strong> <%= @book.print %></p>



<% if @book.comments.empty? %>
  <% else %>
    <p>Comments:
    <ul>
      <% @book.comments.each do |comment| %>
      <li><%= comment.comment %> (on: <%= comment.created_at %>)
        <%= link_to book_path(@book), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} do  %>
        <i class="fa-solid fa-trash"></i> currently deleting the book
      <% end %></li>
      <% end %>
    </ul></p>
    <% end %>

<br>
<br>
<h2>This book is on these lists</h2>
<% @book.listings.each do |listing| %>
<%= List.find(listing.list_id).name  %>
<%= link_to book_path(@book), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} do  %>
        <i class="fa-solid fa-trash"></i> currently deleting the book
      <% end %>
<br>
<% end %>

<br>

<%= link_to book_path(@book), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} do  %>
  <i class="fa-solid fa-trash"></i>
<% end %>


<%= link_to "Delete", book_path(@book), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "btn btn-primary" %>

<%= link_to "Edit", edit_book_path(@book), class: "btn btn-primary" %>

<%= link_to "back", :back, class: "btn btn-primary" %> NOTE: if I did submit a form on the page it does not go back
<%# <%= link_to "Add it on a list", new_listing_path, class: "btn btn-primary" %>

<%= render "comments/form", locals: {book: @book, comment: @comment} %>
<%= render "listings/bookform", locals: {book: @book, listing: @listing} %>

<%# <%= render "listings/form", listing: @listing %>

<%# <%= render "listings/form", locals: {book: @book} %>

app/views/comments/_form.html.erb
  <%= simple_form_for [locals[:book], locals[:comment]] do |f| %>
    <%= f.input :comment %>
    <%= f.input :review %>
    <%= f.input :rating %>
    <%= f.submit "Submit comment", class: "btn btn-primary" %>
  <% end %>

<%# [@book, @comment] %>

app/views/comments/new.html.erb
<%# <%= render "form", locals: {book: @book, comment: @comment} %> %>

<%= simple_form_for [@book, @comment] do |f| %>
  <%= f.input :comment %>
  <%= f.input :review %>
  <%= f.input :rating %>
  <%= f.submit "Submit comment", class: "btn btn-primary" %>
<% end %>

<%# [@book, @comment] %>



<%# here must be a problem %>
<%# <%= simple_form_for locals: {book: @book, comment: @comment} do |f| %> %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyLibary</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render "shared/navbar"%>
    <%= render "shared/flashes" %>
    <main class="container">
    <%= yield %>
    </main>
  </body>
</html>

app/views/listings/_bookform.html.erb
  <%= simple_form_for [locals[:book], locals[:listing]] do |f| %>
    <%= f.association :list %>
    <%= f.input :comment %>
    <%= f.submit "Submit submit to the list", class: "btn btn-primary" %>
  <% end %>

app/views/listings/_form.html.erb
<%= simple_form_for (listing) do |f| %>
  <%= f.association :book  %>
  <%= f.association :list %>
  <%= f.input :comment %>
  <%= f.submit "Submit to the list", class: "btn btn-primary" %>
<% end %>


<%# this is a great listing for listings/new route %>

app/views/listings/_listform.html.erb
  <%= simple_form_for [locals[:list], locals[:listing]] do |f| %>
    <%= f.association :book %>
    <%= f.input :comment %>
    <%= f.submit "Submit submit to the list", class: "btn btn-primary" %>
  <% end %>

app/views/listings/index.html.erb
<h1>Listing index</h1>

<%= link_to "back", :back, class: "btn btn-primary" %>

<% @listings.each do |listing| %>

<%= List.find(listing.list_id).name %> <br>
<%= Book.find(listing.book_id).title %>
<hr>
<% end %>

app/views/listings/new.html.erb
<%= render "form", listing: @listing %>

app/views/lists/_form.html.erb
<%= link_to "back", lists_path, class: "btn btn-primary" %>

<%= simple_form_for locals[:list] do |f| %>
<%= f.input :name, error: "List already exist" %>
<%= f.input :comment %>
<%= f.submit :"Create", class: "btn btn-primary" %>
<% end %>

app/views/lists/edit.html.erb
<p>list update</p>

<%= render "form", list: @list %>

app/views/lists/index.html.erb
<%= link_to "Back to books", books_path, class: "btn btn-primary" %>
<%= link_to "Create new list", new_list_path, class: "btn btn-primary" %>


<%= render "form", locals: {list: @list} %>

<% @lists.each do |list|%>
  <%= link_to list_path(list) do %>
  <h2><%= list.name %></h2>
  <p ><%= list.comment %></p>
  <% end %>
<% end %>

app/views/lists/new.html.erb
<div>
<%= render "form", locals: {list: @list} %>
</div>

app/views/lists/show.html.erb
<%# ||||||||||||||||||||||||||||||||||||||||||||||| %>
<%# List name %>
<%# There will be a description about the list %>

<h1><%= @list.name %></h1>
 <br>
<%= @list.comment %>
<button> Hello button </button>

<%# should be the listings.each where list.id = with the params. %>
<%# and list here all the books which are connected to this %>


<%# ||||||||||||||||||||||||||||||||||||||||||||||| %>

<%# Buttons %>
<%# These are the buttons for the list page %>

<br>
<br>
<%# Back button %>
<%= link_to "Back", :back, class: "btn btn-primary" %>
<%# back to books button %>
<%= link_to "back to books", books_path, class: "btn btn-primary" %>
<%# update button --- NOT WORKING %>
<%# ||||||||||||||||||||||||||||||||||||||||||||||| %>
<%= link_to "update", edit_list_path, class: "btn btn-primary" %>
<%# Delete List button %>
<%= link_to "delete", list_path(@list), data: {turbo_method: :delete, turbo_confirm: "Are you sure you want to delete this list?"}, class: "btn btn-primary" %>


<hr>
<%# ||||||||||||||||||||||||||||||||||||||||||||||| %>
<%# Listed books with this list %>
<div class="container">
<% @list.books.each do |book| %>
  <%= link_to book_path(book) do %>
  <div class="book">
  <h2><%= book.title %></h2>
  <p><%= book.writer %></p>
  <p><%= book.status %></p>
  </div>
  <% end %>
<% end %>
</div>


<%# Renders the form to add a book to this list
This already has the list_id attached. So we only need to choose the book and if we want to add a comment %>
<%= render "listings/listform", locals: {list: @list, listing: @listing}  %>

app/views/pages/home.html.erb
<h1>Welcome to your library</h1>
<p>Here you can find your books</p>


<%= link_to "all books", books_path, class: "btn btn-warning" %>
<%= link_to "create new book", new_book_path, class: "btn btn-warning" %>

<%= link_to "all lists", lists_path, class: "btn btn-warning" %>
<%= link_to "new list", new_list_path, class: "btn btn-warning" %>

<%= link_to "new listing", new_listing_path, class: "btn btn-warning" %>


<%# HAve a currently reading page %>
<h2>Currently Reading</h2>
<%# Currently reading %>
<div class="container">
  <% @books.each do |book| %>
        <% if book.status == "read" %>
        <div class="book">
        <%= link_to book_path(book) do %>
        <h2><%= book.title %></h2>
        <p><%= book.writer%></p>
        <% end %>
        </div>
        <% end %>
      <% end %>
</div>

<h3>Planning to read</h3>
<%# Planning to buy books %>
<%# This year read books, I can use also for the previous years too %>

<h3>Books This Year</h3>


<h3>Last added books </h3>

<h3>Last added books to wishlist</h3>

app/views/shared/_buttons.html.erb
<%# |||||||||||||||| %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<navbar>
  <div class="navbar-container">
    <%= image_tag("placeholder_logo.png", :class => "logo" , :alt => "logo")%>
    <%# <img class="navbar-logo" src="/home/balazs/code/4balage4/my-libary/app/assets/images/placeholder_logo.png" alt="logo" /> %>
    <h2> User's Library</h2>
    <ul>
      <li><p>Home</p></li>
      <li><p>Lists</p></li>
      <li><p>Favorites</p></li>
      <li><p>Whishlist</p></li>
      <li><p>Sign out</p></li>
    </ul>
  </div>
</navbar>